/**
 * Seed/Demo Data for Thanjavur–Kumbakonam pilot launch
 */

export const SEED_CITIES = [
  { id: 'thanjavur', name: 'Thanjavur', nameTamil: 'தஞ்சாவூர்', state: 'Tamil Nadu', isActive: true, baseDeliveryCharge: 30, perKmCharge: 10, peakHourSurcharge: 15, rainSurcharge: 20 },
  { id: 'kumbakonam', name: 'Kumbakonam', nameTamil: 'கும்பகோணம்', state: 'Tamil Nadu', isActive: true, baseDeliveryCharge: 25, perKmCharge: 8, peakHourSurcharge: 10, rainSurcharge: 15 },
];

export const SEED_ZONES = [
  { id: 'tnj-central', name: 'Thanjavur Central', cityId: 'thanjavur', isActive: true, surgeMultiplier: 1.0 },
  { id: 'tnj-south', name: 'Thanjavur South', cityId: 'thanjavur', isActive: true, surgeMultiplier: 1.0 },
  { id: 'tnj-north', name: 'Thanjavur North', cityId: 'thanjavur', isActive: true, surgeMultiplier: 1.0 },
  { id: 'kbk-central', name: 'Kumbakonam Central', cityId: 'kumbakonam', isActive: true, surgeMultiplier: 1.0 },
  { id: 'kbk-east', name: 'Kumbakonam East', cityId: 'kumbakonam', isActive: true, surgeMultiplier: 1.0 },
];

export const SEED_CATEGORIES = [
  { id: 'groceries', name: 'Groceries', nameTamil: 'மளிகை', icon: 'shopping-cart', image: '/images/categories/groceries.jpg', sortOrder: 1, isActive: true },
  { id: 'vegetables', name: 'Vegetables & Fruits', nameTamil: 'காய்கறி & பழங்கள்', icon: 'salad', image: '/images/categories/vegetables.jpg', sortOrder: 2, isActive: true },
  { id: 'meat', name: 'Meat/Chicken/Fish', nameTamil: 'இறைச்சி/கோழி/மீன்', icon: 'drumstick', image: '/images/categories/meat.jpg', sortOrder: 3, isActive: true },
  { id: 'medicines', name: 'Medicines', nameTamil: 'மருந்துகள்', icon: 'pill', image: '/images/categories/medicines.jpg', sortOrder: 4, isActive: true },
  { id: 'bakery', name: 'Bakery', nameTamil: 'பேக்கரி', icon: 'cake-slice', image: '/images/categories/bakery.jpg', sortOrder: 5, isActive: true },
  { id: 'restaurants', name: 'Restaurants', nameTamil: 'உணவகங்கள்', icon: 'utensils', image: '/images/categories/restaurants.jpg', sortOrder: 6, isActive: true },
  { id: 'tea-shops', name: 'Tea Shops/Snacks', nameTamil: 'டீ கடை/சிற்றுண்டி', icon: 'coffee', image: '/images/categories/tea-shops.jpg', sortOrder: 7, isActive: true },
  { id: 'stationery', name: 'Stationery', nameTamil: 'ஸ்டேஷனரி', icon: 'pencil', image: '/images/categories/stationery.jpg', sortOrder: 8, isActive: true },
  { id: 'pet-shop', name: 'Pet Shop', nameTamil: 'செல்லப்பிராணி கடை', icon: 'paw-print', image: '/images/categories/pet-shop.jpg', sortOrder: 9, isActive: true },
  { id: 'flower-shop', name: 'Flower Shop', nameTamil: 'பூ கடை', icon: 'flower-2', image: '/images/categories/flower-shop.jpg', sortOrder: 10, isActive: true },
  { id: 'electronics', name: 'Electronics', nameTamil: 'எலக்ட்ரானிக்ஸ்', icon: 'smartphone', image: '/images/categories/electronics.jpg', sortOrder: 11, isActive: true },
  { id: 'courier', name: 'Courier/Documents', nameTamil: 'கூரியர்/ஆவணங்கள்', icon: 'send', image: '/images/categories/courier.jpg', sortOrder: 12, isActive: true },
  { id: 'water-can', name: 'Water Can', nameTamil: 'தண்ணீர் கேன்', icon: 'droplets', image: '/images/categories/water-can.jpg', sortOrder: 13, isActive: true },
  { id: 'gas-cylinder', name: 'Gas Cylinder', nameTamil: 'காஸ் சிலிண்டர்', icon: 'flame', image: '/images/categories/gas-cylinder.jpg', sortOrder: 14, isActive: true },
  { id: 'milk', name: 'Milk', nameTamil: 'பால்', icon: 'milk', image: '/images/categories/milk.jpg', sortOrder: 15, isActive: true },
  { id: 'cakes', name: 'Cakes', nameTamil: 'கேக்', icon: 'cake', image: '/images/categories/cakes.jpg', sortOrder: 16, isActive: true },
  { id: 'custom-parcel', name: 'Custom Parcel', nameTamil: 'கஸ்டம் பார்சல்', icon: 'package', image: '/images/categories/custom-parcel.jpg', sortOrder: 17, isActive: true },
];

export const SEED_SHOPS = [
  {
    id: 'shop-1',
    name: 'Sri Lakshmi Stores',
    nameTamil: 'ஸ்ரீ லட்சுமி ஸ்டோர்ஸ்',
    description: 'Your daily essentials — fresh groceries, pulses, oils, and more.',
    categoryId: 'groceries',
    tags: ['groceries', 'daily-needs', 'rice', 'oils'],
    phone: '9566700534',
    address: { full: '12, East Main Road, Thanjavur', lat: 10.7870, lng: 79.1378, pincode: '613001', city: 'Thanjavur', zoneId: 'tnj-central' },
    images: { logo: '', banner: '/images/shops/shop-1.jpg', gallery: [] },
    timing: { openTime: '07:00', closeTime: '22:00', days: [0, 1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 100,
    deliveryRadius: 5,
    avgPrepTime: 15,
    rating: 4.6,
    totalRatings: 234,
    totalOrders: 1580,
    commission: 8,
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'shop-2',
    name: 'Fresh Veggies Market',
    nameTamil: 'ஃப்ரெஷ் காய்கறி மார்க்கெட்',
    description: 'Farm-fresh vegetables and fruits delivered to your doorstep.',
    categoryId: 'vegetables',
    tags: ['vegetables', 'fruits', 'organic', 'fresh'],
    phone: '9876543210',
    address: { full: '45, South Street, Thanjavur', lat: 10.7850, lng: 79.1365, pincode: '613001', city: 'Thanjavur', zoneId: 'tnj-central' },
    images: { logo: '', banner: '/images/shops/shop-2.jpg', gallery: [] },
    timing: { openTime: '06:00', closeTime: '20:00', days: [0, 1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 50,
    deliveryRadius: 4,
    avgPrepTime: 10,
    rating: 4.4,
    totalRatings: 156,
    totalOrders: 890,
    commission: 10,
    isApproved: true,
    isFeatured: false,
  },
  {
    id: 'shop-3',
    name: 'Annapoorna Restaurant',
    nameTamil: 'அன்னபூர்ணா உணவகம்',
    description: 'Traditional South Indian meals, tiffin, and snacks.',
    categoryId: 'restaurants',
    tags: ['restaurant', 'south-indian', 'meals', 'tiffin'],
    phone: '9988776655',
    address: { full: '78, Big Street, Kumbakonam', lat: 10.9617, lng: 79.3881, pincode: '612001', city: 'Kumbakonam', zoneId: 'kbk-central' },
    images: { logo: '', banner: '/images/shops/shop-3.jpg', gallery: [] },
    timing: { openTime: '06:30', closeTime: '22:30', days: [0, 1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 80,
    deliveryRadius: 6,
    avgPrepTime: 25,
    rating: 4.7,
    totalRatings: 512,
    totalOrders: 3200,
    commission: 12,
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'shop-4',
    name: 'MedPlus Pharmacy',
    nameTamil: 'மெட்பிளஸ் மருந்தகம்',
    description: 'All medicines, health products, and personal care items.',
    categoryId: 'medicines',
    tags: ['pharmacy', 'medicines', 'health', 'wellness'],
    phone: '9112233445',
    address: { full: '23, Hospital Road, Thanjavur', lat: 10.7900, lng: 79.1400, pincode: '613001', city: 'Thanjavur', zoneId: 'tnj-central' },
    images: { logo: '', banner: '/images/shops/shop-4.jpg', gallery: [] },
    timing: { openTime: '08:00', closeTime: '23:00', days: [0, 1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 0,
    deliveryRadius: 7,
    avgPrepTime: 10,
    rating: 4.5,
    totalRatings: 89,
    totalOrders: 620,
    commission: 5,
    isApproved: true,
    isFeatured: false,
  },
  {
    id: 'shop-5',
    name: 'Royal Bakery',
    nameTamil: 'ராயல் பேக்கரி',
    description: 'Fresh cakes, pastries, cookies, and birthday special cakes.',
    categoryId: 'bakery',
    tags: ['bakery', 'cakes', 'birthday', 'pastries'],
    phone: '9445566778',
    address: { full: '56, Gandhi Road, Kumbakonam', lat: 10.9630, lng: 79.3900, pincode: '612001', city: 'Kumbakonam', zoneId: 'kbk-central' },
    images: { logo: '', banner: '/images/shops/shop-5.jpg', gallery: [] },
    timing: { openTime: '09:00', closeTime: '21:00', days: [1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 150,
    deliveryRadius: 5,
    avgPrepTime: 20,
    rating: 4.8,
    totalRatings: 345,
    totalOrders: 2100,
    commission: 10,
    isApproved: true,
    isFeatured: true,
  },
  {
    id: 'shop-6',
    name: 'Kumbakonam Degree Coffee',
    nameTamil: 'கும்பகோணம் டிகிரி காபி',
    description: 'Authentic filter coffee, tea, snacks and tiffin items.',
    categoryId: 'tea-shops',
    tags: ['coffee', 'tea', 'snacks', 'filter-coffee'],
    phone: '9667788990',
    address: { full: '34, Temple Street, Kumbakonam', lat: 10.9610, lng: 79.3870, pincode: '612001', city: 'Kumbakonam', zoneId: 'kbk-central' },
    images: { logo: '', banner: '/images/shops/shop-6.jpg', gallery: [] },
    timing: { openTime: '05:30', closeTime: '21:00', days: [0, 1, 2, 3, 4, 5, 6] },
    isOpen: true,
    isHolidayMode: false,
    minOrderAmount: 30,
    deliveryRadius: 3,
    avgPrepTime: 10,
    rating: 4.9,
    totalRatings: 678,
    totalOrders: 5400,
    commission: 8,
    isApproved: true,
    isFeatured: true,
  },
];

export const SEED_PRODUCTS = [
  // Sri Lakshmi Stores products
  { id: 'p1', shopId: 'shop-1', categoryId: 'groceries', name: 'Ponni Boiled Rice 5kg', nameTamil: 'பொன்னி புழுங்கல் அரிசி', price: 380, discountPrice: 349, unit: '5 kg', isVeg: true, isAvailable: true, stockQuantity: 50, rating: 4.5, image: '/images/products/rice-grains.jpg' },
  { id: 'p2', shopId: 'shop-1', categoryId: 'groceries', name: 'Toor Dal 1kg', nameTamil: 'துவரம் பருப்பு', price: 180, discountPrice: 159, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 30, rating: 4.3, image: '/images/products/dal-pulses.jpg' },
  { id: 'p3', shopId: 'shop-1', categoryId: 'groceries', name: 'Gingelly Oil 1L', nameTamil: 'நல்லெண்ணெய்', price: 320, discountPrice: undefined, unit: '1 L', isVeg: true, isAvailable: true, stockQuantity: 25, rating: 4.7, image: '/images/products/cooking-oil.jpg' },
  { id: 'p4', shopId: 'shop-1', categoryId: 'groceries', name: 'Sugar 1kg', nameTamil: 'சர்க்கரை', price: 55, discountPrice: 49, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 100, rating: 4.2, image: '/images/products/sugar.jpg' },
  { id: 'p5', shopId: 'shop-1', categoryId: 'groceries', name: 'Tea Powder 500g (3 Roses)', nameTamil: '3 ரோசஸ் டீ தூள்', price: 220, discountPrice: 199, unit: '500 g', isVeg: true, isAvailable: true, stockQuantity: 40, rating: 4.6, image: '/images/products/tea-powder.jpg' },
  { id: 'p6', shopId: 'shop-1', categoryId: 'groceries', name: 'Coconut Oil 500ml', nameTamil: 'தேங்காய் எண்ணெய்', price: 135, discountPrice: undefined, unit: '500 ml', isVeg: true, isAvailable: true, stockQuantity: 35, rating: 4.4, image: '/images/products/coconut-oil.jpg' },
  { id: 'p7', shopId: 'shop-1', categoryId: 'groceries', name: 'Wheat Atta 5kg', nameTamil: 'கோதுமை மாவு', price: 260, discountPrice: 239, unit: '5 kg', isVeg: true, isAvailable: true, stockQuantity: 20, rating: 4.3, image: '/images/products/wheat-atta.jpg' },
  { id: 'p8', shopId: 'shop-1', categoryId: 'groceries', name: 'Urad Dal 1kg', nameTamil: 'உளுந்து', price: 165, discountPrice: undefined, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 28, rating: 4.4, image: '/images/products/dal-pulses.jpg' },

  // Fresh Veggies Market products
  { id: 'p9', shopId: 'shop-2', categoryId: 'vegetables', name: 'Tomato 500g', nameTamil: 'தக்காளி', price: 25, discountPrice: undefined, unit: '500 g', isVeg: true, isAvailable: true, stockQuantity: 80, rating: 4.3, image: '/images/products/tomato.jpg' },
  { id: 'p10', shopId: 'shop-2', categoryId: 'vegetables', name: 'Onion 1kg', nameTamil: 'வெங்காயம்', price: 40, discountPrice: 35, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 100, rating: 4.5, image: '/images/products/onion.jpg' },
  { id: 'p11', shopId: 'shop-2', categoryId: 'vegetables', name: 'Potato 1kg', nameTamil: 'உருளைக்கிழங்கு', price: 35, discountPrice: undefined, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 60, rating: 4.4, image: '/images/products/potato.jpg' },
  { id: 'p12', shopId: 'shop-2', categoryId: 'vegetables', name: 'Banana 1 dozen', nameTamil: 'வாழைப்பழம்', price: 50, discountPrice: 45, unit: '12 pcs', isVeg: true, isAvailable: true, stockQuantity: 40, rating: 4.6, image: '/images/products/banana.jpg' },
  { id: 'p13', shopId: 'shop-2', categoryId: 'vegetables', name: 'Drumstick 250g', nameTamil: 'முருங்கைக்காய்', price: 30, discountPrice: undefined, unit: '250 g', isVeg: true, isAvailable: true, stockQuantity: 30, rating: 4.2, image: '/images/products/drumstick.jpg' },

  // Annapoorna Restaurant products
  { id: 'p14', shopId: 'shop-3', categoryId: 'restaurants', name: 'Meals (Unlimited)', nameTamil: 'மீல்ஸ் (அன்லிமிடெட்)', price: 120, discountPrice: undefined, unit: '1 plate', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.8, image: '/images/products/meals-thali.jpg' },
  { id: 'p15', shopId: 'shop-3', categoryId: 'restaurants', name: 'Chicken Biryani', nameTamil: 'சிக்கன் பிரியாணி', price: 180, discountPrice: 160, unit: '1 plate', isVeg: false, isAvailable: true, stockQuantity: 999, rating: 4.7, image: '/images/products/chicken-biryani.jpg' },
  { id: 'p16', shopId: 'shop-3', categoryId: 'restaurants', name: 'Masala Dosa', nameTamil: 'மசாலா தோசை', price: 60, discountPrice: undefined, unit: '1 pc', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.5, image: '/images/products/masala-dosa.jpg' },
  { id: 'p17', shopId: 'shop-3', categoryId: 'restaurants', name: 'Idli (3 pcs)', nameTamil: 'இட்லி', price: 40, discountPrice: undefined, unit: '3 pcs', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.6, image: '/images/products/idli.jpg' },
  { id: 'p18', shopId: 'shop-3', categoryId: 'restaurants', name: 'Parotta + Salna', nameTamil: 'பரோட்டா + சால்னா', price: 70, discountPrice: undefined, unit: '2 pcs', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.4, image: '/images/products/parotta.jpg' },

  // Royal Bakery products
  { id: 'p19', shopId: 'shop-5', categoryId: 'bakery', name: 'Chocolate Cake 500g', nameTamil: 'சாக்லேட் கேக்', price: 350, discountPrice: 320, unit: '500 g', isVeg: true, isAvailable: true, stockQuantity: 10, rating: 4.8, image: '/images/products/chocolate-cake.jpg' },
  { id: 'p20', shopId: 'shop-5', categoryId: 'bakery', name: 'Puff (Egg)', nameTamil: 'பஃப் (முட்டை)', price: 25, discountPrice: undefined, unit: '1 pc', isVeg: false, isAvailable: true, stockQuantity: 50, rating: 4.3, image: '/images/products/puff-pastry.jpg' },
  { id: 'p21', shopId: 'shop-5', categoryId: 'bakery', name: 'Birthday Cake 1kg', nameTamil: 'பிறந்தநாள் கேக்', price: 650, discountPrice: 599, unit: '1 kg', isVeg: true, isAvailable: true, stockQuantity: 5, rating: 4.9, image: '/images/products/birthday-cake.jpg' },

  // Kumbakonam Degree Coffee
  { id: 'p22', shopId: 'shop-6', categoryId: 'tea-shops', name: 'Filter Coffee', nameTamil: 'ஃபில்டர் காபி', price: 20, discountPrice: undefined, unit: '1 cup', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.9, image: '/images/products/filter-coffee.jpg' },
  { id: 'p23', shopId: 'shop-6', categoryId: 'tea-shops', name: 'Masala Tea', nameTamil: 'மசாலா டீ', price: 15, discountPrice: undefined, unit: '1 cup', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.7, image: '/images/products/masala-tea.jpg' },
  { id: 'p24', shopId: 'shop-6', categoryId: 'tea-shops', name: 'Bajji (5 pcs)', nameTamil: 'பஜ்ஜி', price: 30, discountPrice: undefined, unit: '5 pcs', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.5, image: '/images/products/bajji-bonda.jpg' },
  { id: 'p25', shopId: 'shop-6', categoryId: 'tea-shops', name: 'Bonda (4 pcs)', nameTamil: 'போண்டா', price: 25, discountPrice: undefined, unit: '4 pcs', isVeg: true, isAvailable: true, stockQuantity: 999, rating: 4.6, image: '/images/products/bajji-bonda.jpg' },
];

export const SEED_BANNERS = [
  { id: 'b1', title: 'First Order 50% OFF', image: '/images/banners/b1.jpg', link: '/offers', position: 1, isActive: true },
  { id: 'b2', title: 'Free Delivery on ₹500+', image: '/images/banners/b2.jpg', link: '/offers', position: 2, isActive: true },
  { id: 'b3', title: 'Refer & Earn ₹100', image: '/images/banners/b3.jpg', link: '/profile', position: 3, isActive: true },
];

export const SEED_COUPONS = [
  { id: 'c1', code: 'FIRST50', description: '50% off on your first order', type: 'percentage' as const, value: 50, minOrderAmount: 100, maxDiscount: 100, usageLimit: 1, usedCount: 0, isActive: true },
  { id: 'c2', code: 'NOE30', description: '₹30 off on orders above ₹200', type: 'flat' as const, value: 30, minOrderAmount: 200, maxDiscount: 30, usageLimit: 5, usedCount: 0, isActive: true },
  { id: 'c3', code: 'FREEDEL', description: 'Free delivery on orders above ₹500', type: 'flat' as const, value: 50, minOrderAmount: 500, maxDiscount: 50, usageLimit: 10, usedCount: 0, isActive: true },
];
